### ISSUE TITLE
Unable to detect camera

### ISSUE THREAD

**Issue by ecolgan** [Hermann-SW/fork-raspiraw#1]
This looks very exciting and I'd love to get it going but have i2c issue.  
I have a Raspberry Pi 3 Model B Rev 1.2, a fresh Raspian install (Raspbian GNU/Linux 9 (stretch)) and a Pi NoIR Camera V2.
The camera works fine with raspivid, but I can't see it on the i2c bus and so can't run raspiraw.  
I followed instructions here to set up i2c: https://www.abelectronics.co.uk/kb/article/1/i2c--smbus-and-raspbian-linux.  There is no /dev/i2c-0, but /dev/i2c-1 exists.   i2cdetect -y 1 is empty, so I need to get that working before raspiraw can see it.  lsmod | grep i2c shows i2c-dev and i2c_bcm2835.

Any suggestions to get the camera on the bus?

Thanks

**Comment by Hermann-SW** [comment]
Hi,

I looked up "compile/prepare/use" link on my Raspberry camera link page:
http://stamm-wilbrandt.de/en/Raspberry_camera.html#raspiraw

In case you miss any of the "prepare" section steps please try, the 2nd line append should make i2c-0 appear:
```
sudo apt-get install wiringpi
append  dtparam=i2c_vc=on  to /boot/config.txt
add  i2c-dev  to  /etc/modules-load.d/modules.conf
reboot
```

**Comment by ecolgan** [comment]
That did it, thank you very much.

**Comment by Hermann-SW** [comment]
Please don't forget to bring in (very) bright light for high framerate videos (1000lm did work for 665fps videos, 5000lm for 1000fps).
