### ISSUE TITLE
RPi4 8GB missing from the camera_i2c script 

### ISSUE THREAD

**Issue by totoantibes** [Hermann-SW/fork-raspiraw#3]
Hi Herman,

i noticed that your long_exposure branch  camera_i2c script is missing the following tag for the 8GB model:
d03114.

BTW has this branch been pulled in any master branch? 

Thanks

**Comment by Hermann-SW** [comment]
Hi,

this repo does not have long_exposure branch, this is my branch for old high framerate work.

My "raspiraw" repo has the long-exposure branch:
https://github.com/Hermann-SW/raspiraw

I created a pull request for long-exposure work, but that never made progress: 
https://github.com/raspberrypi/raspiraw/pull/37

Changes for camera-i2c were cherry picked from 6by9 in this pull request:
https://github.com/raspberrypi/raspiraw/pull/36

**Comment by totoantibes** [comment]
Hi hermann,
is there a way to only record an ROI of the frame on the imx477?would like to achieve faster fps in planetary imaging.
Thanks Robert 
    On Wednesday, March 10, 2021 at 10:46:05 AM GMT+1, Hermann Stamm-Wilbrandt ***@***.***> wrote:  
 
 


Hi,

this repo does not have long_exposure branch, this is my branch for old high framerate work.

My "raspiraw" repo has the long-exposure branch:
https://github.com/Hermann-SW/raspiraw

I created a pull request for long-exposure work, but that never made progress:
raspberrypi/raspiraw#37

Changes for camera-i2c were cherry picked from 6by9 in this pull request:
raspberrypi/raspiraw#36
