### ISSUE TITLE
helpers/debug_utils/debug_writer.h not found

### ISSUE THREAD

**Issue by freisei** [Hermann-SW/fork-raspiraw#5]
just trying to build with a fresh installed rpi4.

First error was

`In file included from raspiraw.c:57:
raw_header.h:31:10: fatal error: vc_image_types.h: No such file or directory
   31 | #include "vc_image_types.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
`
can be solved by replacing
`#include "vc_image_types.h"`
with
`#include "vcinclude/vc_image_types.h"`

2nd error:
`root@campi:/usr/local/src/raspiraw_main/fork-raspiraw# ./buildme
In file included from /usr/include/vcinclude/vc_image_types.h:32,
                 from raw_header.h:32,
                 from raspiraw.c:57:
/usr/include/interface/vctypes/vc_image_structs.h:37:10: fatal error: helpers/debug_utils/debug_writer.h: No such file or directory
   37 | #include "helpers/debug_utils/debug_writer.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

this one i have no idea how to solve that... any ideas?

**Comment by puterd** [comment]
I also had the same error on rpi zero  w 2:

```
In file included from raspiraw.c:57:
raw_header.h:31:10: fatal error: vc_image_types.h: No such file or directory
   31 | #include "vc_image_types.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by puterd** [comment]
Using make instead of buildme on the raspiraw install is a workaround for this if you are trying to combine it with dcraw

**Comment by bballinlemur** [comment]
> Using make instead of buildme on the raspiraw install is a workaround for this if you are trying to combine it with dcraw

I am having the same issue you had. What exactly did you do to use make and get around this issue?

**Comment by mirco-ackermann** [comment]
@bballinlemur I had the same issue. I pulled the Makefile from raspiraw and changed the path to the `vc_image_types.h`. With that it builds (after giving a page of warnings because of the aggressive `-W` flags). Tested on Raspbian GNU/Linux 11 (bullseye).

The `Makefile`:
```make
CROSS_COMPILE ?=

CC      := $(CROSS_COMPILE)gcc
CFLAGS ?= -I/opt/vc/include  -pipe -W -Wall -Wextra -g -O0
LDFLAGS ?=
LIBS    := -L/opt/vc/lib -lrt -lbcm_host -lvcos -lmmal_core -lmmal_util -lmmal_vc_client -lvcsm

%.o : %.c
        $(CC) $(CFLAGS) -c -o $@ $<

all: raspiraw

raspiraw: raspiraw.o RaspiCLI.o
        $(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
        -rm -f *.o
        -rm -f raspiraw

```
The change to `raw_header.h`:
```diff
diff --git a/raw_header.h b/raw_header.h
index 7d57dc7..090d159 100644
--- a/raw_header.h
+++ b/raw_header.h
@@ -28,7 +28,7 @@ SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #ifndef RAWHEADER_H_
 #define RAWHEADER_H_
 
-#include "vc_image_types.h"
+#include "interface/vctypes/vc_image_types.h"
 
 #define BRCM_ID_SIG 0x4D435242 /* 'BRCM' */
 #define HEADER_VERSION 111
```

**Comment by Hermann-SW** [comment]
This repo saw last commit in 2019.
Please use "official" raspiraw repo:
[https://github.com/raspberrypi/raspiraw](url)
