### ISSUE TITLE
RPi 4b?

### ISSUE THREAD

**Issue by farm24** [Hermann-SW/fork-raspiraw#6]
is there a way to add support for the Rasberry Pi 4b because I just gen an error when trying to start i2c_camera that the board revision isn't supported?

**Comment by Hermann-SW** [comment]
You can take from official repo:
https://github.com/raspberrypi/raspiraw/blob/master/camera_i2c

**Comment by Hermann-SW** [comment]
This repo saw last commit in 2019, please use "official" repo:
[https://github.com/raspberrypi/raspiraw](url)
