### ISSUE TITLE
Raspiraw and HQ camera: reg error message

### ISSUE THREAD

**Issue by BillieIsRunning** [Hermann-SW/fork-raspiraw#8]
Hi everyone,

I’m currently working on a project, that requires fast image capturing. I’m working with the raspberry pi 4 model B and the imx477 sensor. After I cloned all the repositories and packages required, I tried out raspiraw and it worked. I captured some frames and decoded the images by using dcraw. 
But there is a problem: every time I capture an image, this error message shows up: 
**RaspiRaw: Reg: 380A not found! 
RaspiRaw: Reg: 380B not found!**

It also seems as if there is an image error in all the images I captured using raspiraw.

Do you know why this error message shows up and if this causes the image error? 

Thanks for your help! :)

**Comment by Hermann-SW** [comment]
This old fork of raspiraw saw last commit in 2019, long before HQ camera arrived.
380A is a ov5647 register, the Raspberry v1 camera.
Please use the "official" rapiraw repo having HQ camera support:
[https://github.com/raspberrypi/raspiraw](url)

**Comment by BillieIsRunning** [comment]
Thanks for your quick reply. I tried to open the link, but it didn't work.

**Comment by vonj** [comment]
https://github.com/raspberrypi/raspiraw


Otherwise just browse/search to it manually

**Comment by Hermann-SW** [comment]
Sorry, my fault, @vonj's link does work

**Comment by BillieIsRunning** [comment]
Thank you! 👍
